#!/bin/bash
#SBATCH --qos pq_chapagap
#SBATCH --account=acc_chapagap
#SBATCH --partition GPU_chapagap

# Number of nodes
#SBATCH -N 1

# Number of tasks
#SBATCH -n 34
#SBACTH --mem 95092
# Number of GPUs per node
#SBATCH --gres=gpu:2
# Specify server to run this job on
#SBATCH -w g012
#SBATCH --output=log3

##########################################################
# Setup envrionmental variable. 
##########################################################
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
. /home/share/Modules/4.1.3/init/profile.sh
module load namd/2.13
pwd; hostname; date

echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"

##########################################################
##########################################################

for p in {1..6}; do charmrun  ++ppn $OMP_NUM_THREADS ++p $OMP_NUM_THREADS `which namd2` +idlepoll +ignoresharing  step6.${p}_equilibration.inp > step6.${p}_equilibration.log ; done

#charmrun  ++ppn $OMP_NUM_THREADS ++p $OMP_NUM_THREADS `which namd2` +idlepoll +ignoresharing  step4_equilibration.inp > step4_equilibration.log
#charmrun  ++ppn $OMP_NUM_THREADS ++p $OMP_NUM_THREADS `which namd2` +idlepoll +ignoresharing  harmonic.inp > harmonic.log

date

